dataset_path: QHQK/conversation_hall_binary_v1
dataset_kwargs:
  token: True
task: "lhqa_discrim_conversation_binary"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.lhqa_doc_to_visual
doc_to_text: !function utils.lhqa_doc_to_text_binary
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 128
  temperature: 0
  top_p: 0
  num_beams: 1
  do_sample: false
process_results: !function utils.lhqa_process_results
metric_list:
  - metric: lhqa_accuracy
    aggregation: !function utils.lhqa_aggregate_accuracy
    higher_is_better: true
  - metric: lhqa_precision
    aggregation: !function utils.lhqa_aggregate_precision
    higher_is_better: true
  - metric: lhqa_recall
    aggregation: !function utils.lhqa_aggregate_recall
    higher_is_better: true
  - metric: lhqa_f1_score
    aggregation: !function utils.lhqa_aggregate_f1_score
    higher_is_better: true
  - metric: lhqa_yes_ratio
    aggregation: !function utils.lhqa_aggregate_yes_ratio
    higher_is_better: true
metadata:
  - version: 0.0