dataset_path: QHQK/description_hall_choice_v2
dataset_kwargs:
  token: True
task: "lhqa_discrim_description_ppl"
test_split: test
output_type: multiple_choice
doc_to_visual: !function utils.lhqa_doc_to_visual
doc_to_text: !function utils.lhqa_doc_to_text_ppl
doc_to_choice : !function utils.lhqa_doc_to_choice
doc_to_target: !function utils.lhqa_doc_to_mc_target

metric_list:
  - metric: acc
metadata:
  - version: 0.0